categories:
  - Blog
  - Recipes
  - Keto
tags:
  - Blog
  - Keto
  - Travel
  - Food
  - Recipes

gems:


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"


_options:
  image_path:
    width: 90
    height: 120
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
  content:
    width: 90
    height: 120
    resize_style: "cover"
    mime_type: "image/png"

permalink: /:title/
